ChaseRacer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ChaseRacer.Models;

namespace ChaseRacer.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ChaseRacer/Controllers/LegController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ChaseRacer.Data;
using ChaseRacer.Models;
using Microsoft.AspNetCore.Mvc;

namespace ChaseRacer.Controllers
{
    public class LegController : Controller
    {
        private ILegData legData;
        public LegController(ILegData legData)
        {
            this.legData = legData;
        }
        public IActionResult Index()
        {
            var legs = legData.GetLegs();
            return View(legs);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var leg = new Leg();
            return View(leg);
        }

        [HttpPost]
        public IActionResult Create(Leg leg)
        {
            var a = legData.AddLeg(leg);
            if (a)
            {
                return RedirectToAction("Index");
            } else
            {
                return View(leg);
            }
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var leg = legData.GetLeg(id);
            return View(leg);
        }

        [HttpPost]
        public IActionResult Edit(Leg leg)
        {
            var a = legData.EditLeg(leg);
            if (a)
            {
                return RedirectToAction("Index");
            } else
            {
                return View(leg);
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var leg = legData.GetLeg(id);
            return View(leg);
        }

        public IActionResult Delete(Leg leg)
        {
            var a = legData.RemoveLeg(leg);
            if (a)
            {
                return RedirectToAction("Index");
            }
            else { return View(leg); }
        }

        public IActionResult Details(int id)
        {
            var leg = legData.GetLeg(id);
            return View(leg);
        }
    }
}

ChaseRacer/Controllers/RunnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ChaseRacer.Data;
using ChaseRacer.Models;
using Microsoft.AspNetCore.Mvc;

namespace ChaseRacer.Controllers
{
    public class RunnerController : Controller
    {
        private readonly IRunnerData runnerData;
        public RunnerController(IRunnerData runnerData)
        {
            this.runnerData = runnerData;
        }
        public IActionResult Index()
        {
            var model = runnerData.GetRunners();
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var model = new Runner() { };
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(Runner runner)
        {
            if (ModelState.IsValid)
            {
                runnerData.AddRunner(runner);
                return RedirectToAction("Index");
            }
            else
            {
                return View(runner);
            }
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = runnerData.GetRunner(id);
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(Runner runner)
        {
            if (ModelState.IsValid)
            {
                runnerData.UpdateRunner(runner);
                return RedirectToAction("Index");
            } else
            {
                return View(runner);
            }
        }

        public IActionResult Details(int id)
        {
            var model = runnerData.GetRunner(id);
            return View(model);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var model = runnerData.GetRunner(id);
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Runner runner)
        {
            if (ModelState.IsValid)
            {
                runnerData.RemoveRunner(runner);
                return RedirectToAction("Index");
            }
            else
            {
                return View(runner);
            }
        }


    }
}

ChaseRacer/Views/Home/Index.cshtml
@page "/"


<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ChaseRacer/Views/Leg/Create.cshtml
@model ChaseRacer.Models.Leg

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Leg</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LegId" class="control-label"></label>
                <input asp-for="LegId" class="form-control" />
                <span asp-validation-for="LegId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LegDistance" class="control-label"></label>
                <input asp-for="LegDistance" class="form-control" />
                <span asp-validation-for="LegDistance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LegNumber" class="control-label"></label>
                <input asp-for="LegNumber" class="form-control" />
                <span asp-validation-for="LegNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ChaseRacer/Views/Leg/Delete.cshtml
@model ChaseRacer.Models.Leg

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Leg</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LegId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LegId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LegDistance)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LegDistance)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LegNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LegNumber)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ChaseRacer/Views/Leg/Details.cshtml
@model ChaseRacer.Models.Leg

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Leg</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LegId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LegId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LegDistance)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LegDistance)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LegNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LegNumber)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.LegId }) |
    <a asp-action="Index">Back to List</a>
</div>

ChaseRacer/Views/Leg/Edit.cshtml
@model ChaseRacer.Models.Leg

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Leg</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LegId" class="control-label"></label>
                <input asp-for="LegId" class="form-control" />
                <span asp-validation-for="LegId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LegDistance" class="control-label"></label>
                <input asp-for="LegDistance" class="form-control" />
                <span asp-validation-for="LegDistance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LegNumber" class="control-label"></label>
                <input asp-for="LegNumber" class="form-control" />
                <span asp-validation-for="LegNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ChaseRacer/Views/Leg/Index.cshtml
@model IEnumerable<ChaseRacer.Models.Leg>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LegId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LegDistance)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LegNumber)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LegId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LegDistance)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LegNumber)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {  id=item.LegId  }) |
                @Html.ActionLink("Details", "Details", new {  id=item.LegId  }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.LegId  })
            </td>
        </tr>
}
    </tbody>
</table>

ChaseRacer/Views/Runner/Create.cshtml
@model ChaseRacer.Models.Runner

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Runner</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RunnerNumber" class="control-label"></label>
                <input asp-for="RunnerNumber" class="form-control" />
                <span asp-validation-for="RunnerNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NickName" class="control-label"></label>
                <input asp-for="NickName" class="form-control" />
                <span asp-validation-for="NickName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaceMinutes" class="control-label"></label>
                <input asp-for="PaceMinutes" class="form-control" />
                <span asp-validation-for="PaceMinutes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaceSeconds" class="control-label"></label>
                <input asp-for="PaceSeconds" class="form-control" />
                <span asp-validation-for="PaceSeconds" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VanDesignation" class="control-label"></label>
                <input asp-for="VanDesignation" class="form-control" />
                <span asp-validation-for="VanDesignation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ChaseRacer/Views/Runner/Delete.cshtml
@model ChaseRacer.Models.Runner

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Runner</h4>
    <hr />
    <dl class="row">
            @Html.HiddenFor(model => model.RunnerId)
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RunnerNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RunnerNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NickName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NickName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaceMinutes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaceMinutes)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaceSeconds)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaceSeconds)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VanDesignation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VanDesignation)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ChaseRacer/Views/Runner/Details.cshtml
@using FirstBlazorApp.Pages;
@using Microsoft.AspNetCore.Components.Web;
@model ChaseRacer.Models.Runner



<h1>Details</h1>

<div>
    <h4>Runner</h4>
    <hr />
    <div class="row">
        <div class="col-8">
            <div class="row">
                <div class="col-2">
                    @Html.DisplayNameFor(model => model.RunnerNumber)
                </div>
                <div class="col-10">
                    @Html.DisplayFor(model => model.RunnerNumber)
                </div>
            </div>
            <div class="row">
                <div class="col-2">
                    @Html.DisplayNameFor(model => model.NickName)
                </div>
                <div class="col-10">
                    @Html.DisplayFor(model => model.NickName)
                </div>
            </div>
            <div class="row">
                <div class="col-2">
                    @Html.DisplayNameFor(model => model.PaceMinutes)
                </div>
                <div class="col-10">
                    @(Model.RunnerPace())
                </div>
            </div>
            <div class="row">
                <div class="col-2">
                    @Html.DisplayNameFor(model => model.VanDesignation)
                </div>
                <div class="col-10">
                    @Html.DisplayFor(model => model.VanDesignation)
                </div>
            </div>
        </div>
        <div class="col-4">
            <div id="CalculateLegTimes">
                @(await Html.RenderComponentAsync<CalculateLegTimes>(RenderMode.ServerPrerendered))
            </div>
        </div>
    </div>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.RunnerId }) |
    <a asp-action="Index">Back to List</a>
</div>

ChaseRacer/Views/Runner/Edit.cshtml
@model ChaseRacer.Models.Runner

@{
    ViewData["Title"] = "Edit";
    var selectListItems = Html.GetEnumSelectList(typeof(Van));
}

<h1>Edit</h1>

<h4>Runner</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RunnerId" class="control-label"></label>
                <input asp-for="RunnerId" class="form-control" />
                <span asp-validation-for="RunnerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RunnerNumber" class="control-label"></label>
                <input asp-for="RunnerNumber" class="form-control" />
                <span asp-validation-for="RunnerNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NickName" class="control-label"></label>
                <input asp-for="NickName" class="form-control" />
                <span asp-validation-for="NickName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaceMinutes" class="control-label"></label>
                <input asp-for="PaceMinutes" class="form-control" />
                <span asp-validation-for="PaceMinutes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaceSeconds" class="control-label"></label>
                <input asp-for="PaceSeconds" class="form-control" />
                <span asp-validation-for="PaceSeconds" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VanDesignation" class="control-label"></label>
                @Html.DropDownListFor(model => model.VanDesignation, selectListItems, new { @class = "form-control" })
                <span asp-validation-for="VanDesignation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ChaseRacer/Views/Runner/Index.cshtml
@using FirstBlazorApp.Pages;
@using Microsoft.AspNetCore.Components.Web;
@model IEnumerable<ChaseRacer.Models.Runner>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RunnerNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NickName)
            </th>
            <th>
                Pace
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VanDesignation)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RunnerNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NickName)
            </td>
            <td>
                @(item.RunnerPace())
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VanDesignation)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.RunnerId }) |
                @Html.ActionLink("Details", "Details", new { id=item.RunnerId  }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.RunnerId  })
            </td>
        </tr>
}
    </tbody>
</table>

ChaseRacer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChaseRacer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <base href="~/"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ChaseRacer</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Runner" asp-action="Index">Runners</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Leg" asp-action="Index">Legs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - ChaseRacer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="_framework/blazor.server.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>